### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by Gerrxt07** [Qbox-project/qb-adminmenu#6]
[ script:qb-adminmenu] SCRIPT ERROR: @qb-adminmenu/server/main.lua:251: attempt to index a nil value (local 'path')
[ script:qb-adminmenu] > fn (@qb-adminmenu/server/main.lua:251)

**Comment by BerkieBb** [comment]
You need interact-sound or change the Config.SoundScriptName to your sound resource for that error to go away currently, but we can also add a condition to not run if the resource is not present
